### ISSUE TITLE
fails to build with webdriver-0.13

### ISSUE THREAD

**Issue by juhp** [dfordivam/hspec-webdriver-clone#5]
```
       Building library for hspec-webdriver-1.2.2...
       [1 of 1] Compiling Test.Hspec.WebDriver
       /home/curators/work/unpack-dir/unpacked/hspec-webdriver-1.2.2-437bc731e23651c3bd6270b644deacf274a84ad8de9fa9ba15b4e98ed7801d45/Test/Hspec/WebDriver.hs:117:24: error: [GHC-61689]
           Module ‘Test.WebDriver’ does not export ‘WD’.
           |
       117 | import Test.WebDriver (WD, Capabilities)
           |                        ^^
       
       /home/curators/work/unpack-dir/unpacked/hspec-webdriver-1.2.2-437bc731e23651c3bd6270b644deacf274a84ad8de9fa9ba15b4e98ed7801d45/Test/Hspec/WebDriver.hs:120:1: error: [GHC-61948]
           Could not find module ‘Test.WebDriver.Config’.
           Perhaps you meant Test.WebDriver.Profile (from webdriver-0.13.0.0)
           Use -v to see a list of the files searched for.
           |
       120 | import qualified Test.WebDriver.Config as W
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       
       /home/curators/work/unpack-dir/unpacked/hspec-webdriver-1.2.2-437bc731e23651c3bd6270b644deacf274a84ad8de9fa9ba15b4e98ed7801d45/Test/Hspec/WebDriver.hs:122:1: error: [GHC-61948]
           Could not find module ‘Test.WebDriver.Session’.
           Perhaps you meant
             Test.WebDriver.Keys (from webdriver-0.13.0.0)
             Test.WebDriver.Waits (from webdriver-0.13.0.0)
             Test.WebDriver.Profile (from webdriver-0.13.0.0)
           Use -v to see a list of the files searched for.
           |
       122 | import qualified Test.WebDriver.Session as W
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dfordivam** [comment]
@juhp I had a look at `webdriver` 0.14, my understanding is that it solves the core issue which `hspec-webdriver` is trying to solve by keeping the session state managed entirely on the browser/geckodriver side. And this is apparent from the fact that `webdriver` now has a test suite employing `hspec`. I tried to build a `hspec` myself using just the `webdriver` and it was fairly straightforward.

What this means is that `hspec-webdriver` is mostly obsolete going forward and users should be able to make use of `webdriver` + `hspec`.

**Comment by juhp** [comment]
Sure makes sense - feel free to close if it is obsolete
